name: 'metal'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  project:
    env:
      METAL_AUTH_TOKEN: ${{ secrets.METAL_AUTH_TOKEN }}
    runs-on: ubuntu-latest
    # TODO(displague) PROJECT_ID should also be globalized
    steps:
    - run: find ${{ runner.temp }}/.. -ls 
    - id: metal-project
      uses: equinix-labs/metal-project-action@v0.11.0
    - name: Use the Project SSH Key environment (display it)
      run: |
        echo ${{ env.METAL_SSH_PRIVATE_KEY_FILE }}
        echo $METAL_SSH_PUBLIC_KEY_FILE
    - name: Use the Project ID outputs (display it)
      run: |
        echo Equinix Metal Project "$PROJECT_NAME" has ID "$PROJECT_ID"
      env:
        PROJECT_ID: ${{ steps.metal-project.outputs.projectID }}
        PROJECT_NAME: ${{ steps.metal-project.outputs.projectName }}
    - name: Project Delete
      uses: equinix-labs/metal-sweeper-action@v0.4.0
      env:
        METAL_PROJECT_ID: ${{ steps.metal-project.outputs.projectID }}
